version: '2'
services:

  db:
    environment:
      - POSTGRES_PASSWORD=odoo_db_pass
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    image: postgres:11
    networks:
      - backend
    volumes:
      - "./var/data/postgres/11/pgdata:/var/lib/postgresql/data/pgdata"

  odoo:
    image: pico-odoo13
    build: .
    depends_on:
      - db
    networks:
      - backend
      - frontend
    volumes:
      - "./odoo.conf:/etc/odoo/odoo.conf"
      - "./var/data/odoo:/var/lib/odoo"
      - "./:/opt/odoo/pico"

  nginx:
    depends_on:
      - odoo
    image: nginx:1.15
    networks:
      - frontend
    volumes:
      - "./nginx-site.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx-proxy_params:/etc/nginx/proxy_params"


networks:
  backend:
  frontend:
