version: '2'
services:

  db: &db
    environment:
      - POSTGRES_PASSWORD=odoo_db_pass
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    image: postgres:11
    networks:
      - backend
    volumes:
      # - "./data/postgres/11/pgdata:/var/lib/postgresql/data/pgdata"
      - "odoopgdata:/var/lib/postgresql/data/pgdata"

  odoo: &odoo
    image: pico-odoo15
    build: .
    command: -- --dev reload,xml -u pico_mrp
    depends_on:
      - db
    networks:
      - odoo
      - backend
    ports:
      - "8069:8069"
    volumes:
      - "./odoo.conf:/etc/odoo/odoo.conf"
      - "./data/odoo:/var/lib/odoo" # MUST BE WRITABLE by odoo CONTAINER USER - mkdir -p data/odoo && chown 104 data/odoo
      # - "odoodata:/var/lib/odoo" # MUST BE WRITABLE by odoo CONTAINER USER
      - "./:/opt/odoo/pico"

  tdb:
    <<: *db
    networks:
      - t
    volumes:
      - "todoopgdata:/var/lib/postgresql/data/pgdata"

  todoo:
    <<: *odoo
    command: /opt/odoo/pico/test.sh
    depends_on:
      - tdb
    ports:
      - "1111:8069"
    networks:
      - t
    volumes:
      - "./todoo.conf:/etc/odoo/odoo.conf"
      # - "./data/odoo:/var/lib/odoo" # MUST BE WRITABLE by odoo CONTAINER USER
      - "./:/opt/odoo/pico"

networks:
  t:
  backend:
  odoo:
    external: true
volumes:
  todoopgdata:
  odoopgdata:
  # odoodata:
